resources:
  - name: git-repository
    type: git
    source:
      uri: https://github.com/xebia-france/XOverflow.git
      branch: enh/rewriteBaseCode
  - name: xoverflow-image
    type: docker-image
    source:
      repository: jpthiery/xoverflow
      username: {{dockerLogin}}
      password: {{dockerPassword}}
jobs:
- name: build and test
  plan:
  - get: git-repository
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      inputs:
        - name: git-repository
      outputs:
        - name: built
      run:
        path: sh
        args:
        - -exc
        - |
          pwd && ls -l && cd git-repository && mvn clean install && cp target/xoverflow-*.jar ../built/xoverflow.jar && cp etc/docker/Dockerfile ../built/Dockerfile && ls -l ../built
  - put: xoverflow-image
    params:
      build: built
